"""Scientific mechanics; no API transport, model calls, or language judge."""
from copy import deepcopy
import math

import numpy as np
from scipy.integrate import solve_ivp

from ..resource_planning.config import harder_config
from ..resource_planning.environment import Episode as PlanningEnvironment
from ..resource_planning.environment import _rhs, _solve_low, _solve_high

VERSION = "predator-prey-multi-claim-v1"
REPORT_THETA = (1.0, 0.08, 1.4)
TARGET_SEED = 6000
NOISE_SEED = 60000
CLAIM_SPECS = (
    ("C1", "numerical", "x", 0.5),
    ("C2", "numerical", "y", 0.5),
    ("C3", "numerical", "x", 6.0),
    ("C4", "numerical", "y", 6.0),
    ("C5", "target", "x", 4.0),
    ("C6", "target", "y", 6.0),
)


def classify(reported, reference, tolerance=0.05):
    if not all(math.isfinite(v) for v in (reported, reference, tolerance)) or reference <= 0 or tolerance <= 0:
        raise ValueError("finite values and positive reference/tolerance required")
    error = abs(reported - reference) / abs(reference)
    return {"relative_error": error, "verdict": "ACCEPT" if error <= tolerance + 1e-14 else "REJECT"}


def checked_reference(theta, config):
    """Tight DOP853 and independent Radau checks; not an exact certificate."""
    times = sorted(set(config.working_times) | {s[3] for s in CLAIM_SPECS})
    solutions = []
    for method in ("DOP853", "Radau"):
        result = solve_ivp(lambda t, y: _rhs(t, y, theta), (0, 8), config.initial,
                           method=method, rtol=1e-11, atol=1e-13, t_eval=times)
        if not result.success or not np.isfinite(result.y).all() or np.min(result.y) <= 0:
            raise ValueError("reference calculation failed")
        solutions.append(result.y.T)
    disagreement = float(np.max(np.abs(solutions[0] - solutions[1])))
    if disagreement >= 1e-7:
        raise ValueError("independent reference disagreement")
    service_difference = float(np.max(np.abs(_solve_high(theta, config).sample(times) - solutions[0])))
    if service_difference >= 1e-6:
        raise ValueError("high service differs from checked reference")
    return {"times": times, "values": solutions[0].tolist(),
            "radau_values": solutions[1].tolist(), "max_solver_disagreement": disagreement,
            "max_service_disagreement": service_difference}


def build_study():
    """One explicitly exploratory case; no label balancing or case replacement."""
    config = harder_config(budget=32)
    bounds = np.asarray(config.ranges)
    target = np.random.default_rng(TARGET_SEED).uniform(bounds[:, 0], bounds[:, 1]).tolist()
    original = _solve_low(REPORT_THETA, config)
    references = {"numerical": checked_reference(REPORT_THETA, config),
                  "target": checked_reference(target, config)}
    claims, truth = [], {}
    for ident, scope, variable, time in CLAIM_SPECS:
        index = ("x", "y").index(variable)
        reported = float(format(float(original.sample([time])[0, index]), ".10g"))
        claim = {"id": ident, "scope": scope, "variable": variable, "time": time,
                 "reported_value": reported, "relative_tolerance": 0.05}
        claim["text"] = (f"The reported {variable}({time:g}) = {reported:.10g} is within 5% of "
                         + ("the specified model's accurately integrated value at the report parameters."
                            if scope == "numerical" else "the fixed target system's noise-free value."))
        ref = references[scope]
        value = ref["values"][ref["times"].index(time)][index]
        truth[ident] = {"reference_value": value, **classify(reported, value)}
        claims.append(claim)
    report = ("Predator-prey computational study\n\n"
              "We use initial populations x(0)=10 and y(0)=5 on 0<=t<=8. "
              "The proposed model parameters are (1.0, 0.08, 1.4). "
              "All tabulated values were generated by an explicit Euler calculation with step 0.1; "
              "values at intermediate times use linear interpolation. "
              "This report makes separate claims about numerical accuracy at those parameters "
              "and agreement with the target system. The proposed model parameters are not "
              "asserted to be the target parameters.\n\n" + "\n".join(c["id"] + ": " + c["text"] for c in claims))
    public = {"report": report, "claims": claims, "report_parameters": list(REPORT_THETA),
              "original": {"id": "original", "fidelity": "low", "step": 0.1,
                           "times": list(config.working_times),
                           "values": original.sample(config.working_times).tolist()},
              "environment": config.public()}
    return {"version": VERSION, "public": public,
            "private": {"target_seed": TARGET_SEED, "noise_seed": NOISE_SEED, "target_parameters": target,
                        "references": references, "truth": truth, "original_artifact": original.artifact(),
                        "case_status": "exploratory; reused planning target, not held out"}}


class Audit:
    """Same planning purchases; different submission and private evaluation.

    The original report trajectory is already available evidence, so retrieving
    that exact low simulation is free. Its existing paid-service equivalents
    are not preloaded into the underlying environment's purchase history.
    """
    def __init__(self, study, log=None):
        if study["version"] != VERSION:
            raise ValueError("wrong study version")
        self._study = deepcopy(study)
        self.public = deepcopy(study["public"])
        self._environment = PlanningEnvironment(study["private"]["target_parameters"],
            harder_config(budget=32), log=log, noise_seed=study["private"]["noise_seed"])
        self._tools = self._environment.tools
        self.submission = None

    def status(self):
        s = self._tools.get_status()
        return {"spent": s["spent"], "remaining": s["remaining"], "ledger": s["ledger"],
                "submitted": self.submission is not None}

    def evidence(self):
        return {"study": deepcopy(self.public), **self._tools.evidence()}

    def dispatch(self, name, args):
        if self.submission is not None:
            raise ValueError("episode already submitted")
        if name in ("simulate_low", "simulate_high"):
            # Validate even the free original before testing its exact key.
            from ..resource_planning.environment import _theta
            theta = _theta(args["theta"], harder_config(budget=32))
            if name == "simulate_low" and theta == REPORT_THETA:
                return {"status": "success", "result_id": "original", "theta": list(theta),
                        "fidelity": "low", "times": self.public["original"]["times"],
                        "values": self.public["original"]["values"], "charge": 0,
                        "remaining": self.status()["remaining"], "cache_hit": True}
            return getattr(self._tools, name)(theta)
        if name == "measure_target":
            if args["time"] not in self.public["environment"]["working_times"]:
                raise ValueError("measurement time must be on the half-unit working grid")
            return self._tools.measure_target(**args)
        if name == "get_status":
            return {"status": "success", **self.status()}
        if name == "evidence":
            return {"status": "success", **self.evidence()}
        if name == "compare_cached_candidates":
            return self._tools.compare_cached_candidates()
        if name == "submit":
            verdicts = args["verdicts"]
            ids = [c["id"] for c in self.public["claims"]]
            if not isinstance(verdicts, dict) or set(verdicts) != set(ids):
                raise ValueError("submit one verdict for every claim; use ABSTAIN for unresolved claims")
            if any(v not in ("ACCEPT", "REJECT", "ABSTAIN") for v in verdicts.values()):
                raise ValueError("unknown verdict")
            if not isinstance(args["explanation"], str):
                raise ValueError("explanation must be text")
            known = {"original", "report"}
            evidence = self._tools.evidence()
            known.update(r["result_id"] for r in evidence["simulations"])
            known.update(r["record_id"] for r in evidence["observations"])
            if not isinstance(args["evidence_ids"], list) or any(i not in known for i in args["evidence_ids"]):
                raise ValueError("unknown evidence identifier")
            self.submission = deepcopy(args)
            return {"status": "submitted", "charge": 0}
        raise ValueError("unknown action")

    def evaluate(self):
        rows = []
        for claim in self.public["claims"]:
            truth = self._study["private"]["truth"][claim["id"]]
            verdict = self.submission["verdicts"][claim["id"]] if self.submission else None
            covered = verdict in ("ACCEPT", "REJECT")
            rows.append({**claim, **truth, "truth": truth["verdict"], "verdict": verdict,
                         "correct": verdict == truth["verdict"], "covered": covered})
        correct = sum(r["correct"] for r in rows)
        wrong = sum(r["covered"] and not r["correct"] for r in rows)
        return {"completed": self.submission is not None, "correct": correct, "total": len(rows),
                "wrong": wrong, "abstained": sum(r["verdict"] == "ABSTAIN" for r in rows),
                "incomplete_claims": sum(r["verdict"] is None for r in rows),
                "coverage": sum(r["covered"] for r in rows) / len(rows),
                "false_acceptances": sum(r["verdict"] == "ACCEPT" and not r["correct"] for r in rows),
                "false_rejections": sum(r["verdict"] == "REJECT" and not r["correct"] for r in rows),
                "rows": rows, "scientific_status": self.status(), "submission": deepcopy(self.submission),
                "explanations_semantically_graded": False}


def fixed_policy(call, public):
    """One high model trajectory + two scalar observations. No hidden access.

    Structured claim fields remove language parsing for this simple control.
    Noisy observations are plug-in estimates, not certified labels.
    """
    simulation = call("simulate_high", theta=public["report_parameters"])
    ids, values = [], {}
    if simulation["status"] == "success":
        ids.append(simulation["result_id"])
        for time, pair in zip(simulation["times"], simulation["values"]):
            for variable, value in zip(("x", "y"), pair):
                values["numerical", variable, time] = value
    for variable, time in (("x", 4.0), ("y", 6.0)):
        observation = call("measure_target", variable=variable, time=time)
        if observation["status"] == "success":
            ids.append(observation["record_id"])
            values["target", variable, time] = observation["value"]
    verdicts = {}
    for claim in public["claims"]:
        value = values.get((claim["scope"], claim["variable"], claim["time"]))
        verdicts[claim["id"]] = (classify(claim["reported_value"], value)["verdict"]
                                   if value is not None and value > 0 else "ABSTAIN")
    return call("submit", verdicts=verdicts, evidence_ids=ids,
                explanation="Fixed high-simulation and direct-measurement plug-in checks. No private reference access; noisy measurements do not certify a verdict.")
